# Generated by Django 4.2.11 on 2024-04-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('Review', 'Рассмотрение'), ('Accepted', 'Принято'), ('Denied', 'Отклонено')], default='New', max_length=50),
        ),
    ]
