# Generated by Django 4.2.11 on 2024-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_bugreport_status_featurerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
